# Generated by Django 4.2 on 2023-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkContrato',
            fields=[
                ('seq_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('num_empresa', models.IntegerField(blank=True, null=True)),
                ('cod_pessoa', models.IntegerField()),
                ('numero_contrato', models.IntegerField(blank=True, null=True)),
                ('vl_contrato', models.FloatField()),
                ('dt_inicio_contrato', models.DateField()),
                ('dt_fim_contrato', models.DateField()),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('dt_contrato', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ek_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkContratoDetalhe',
            fields=[
                ('seq_contrato_detalhe', models.AutoField(primary_key=True, serialize=False)),
                ('seq_contrato', models.IntegerField(blank=True, db_column='seq_contrato', null=True)),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_item_contrato', models.CharField(blank=True, max_length=200, null=True)),
                ('vl_item_contrato', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ek_contrato_detalhe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkPessoa',
            fields=[
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_pessoa', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'ek_pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EkProduto',
            fields=[
                ('cod_produto', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('desc_produto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ek_produto',
                'managed': False,
            },
        ),
    ]
